name: pars_validator
description: "A lightweight Flutter library for validating Persian-specific data formats like national codes,bank card numbers, phone numbers, Shamsi dates, and more."
version: 0.5.9
homepage: https://github.com/MohammadTaghipour/pars_validator

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/operators/
    - assets/icons/banks/
