name: pars_validator
description: "A lightweight Flutter library for validating Persian-specific data formats like national codes,bank card numbers, phone numbers, Shamsi dates, and more."
version: 0.1.0
homepage: https://github.com/MohammadTaghipour/pars_validator

environment:
  sdk: ^3.5.3
